name = "identity-reconciler"
main = "dist/worker.js"
compatibility_date = "2023-06-10"
minify = true

[placement]
mode = "smart"

[vars]
# Necessary secrets are:
# - DATABASE_URL

[build]
command = "pnpm run build"