name: deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: publish
        run: pnpm run deploy
