name: deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: install dependencies
        run: pnpm install
      - name: run migrations
        run: pnpm run migrate
      - name: publish
        run: pnpm run deploy
