name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
      - uses: pnpm/action-setup@v2
      - name: check formating
        run: pnpm run format:check
      - name: lint
        run: pnpm run lint
      - name: test
        run: pnpm run test
