name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: install dependencies
        run: pnpm install
      - name: check formating
        run: pnpm run format:check
      - name: lint
        run: pnpm run lint
      - name: test
        run: pnpm run test
